#ifndef BOXC_PTRACE_H
#define BOXC_PTRACE_H

#define PTRACE_TRACEME PT_TRACE_ME
#define PTRACE_PEEKTEXT PT_READ_I
#define PTRACE_PEEKDATA PT_READ_D
#define PTRACE_POKETEXT PT_WRITE_I
#define PTRACE_POKEDATA PT_WRITE_D
#define PTRACE_CONT PT_CONTINUE
#define PTRACE_KILL PT_KILL
#define PTRACE_SINGLESTEP PT_STEP
#define PTRACE_GETREGS PT_GETREGS
#define PTRACE_SETREGS PT_SETREGS
#define PTRACE_GETFPREGS PT_GETFPREGS
#define PTRACE_SETFPREGS PT_SETFPREGS
#define PTRACE_ATTACH PT_ATTACH
#define PTRACE_DETACH PT_DETACH
#define PTRACE_SYSCALL PT_SYSCALL

extern int ptrace(int _request, pid_t _pid, caddr_t _addr, int _data);

#endif
